'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    // type
    // 0 : 온라인
    // 1 : 오프라인
    
     const createdAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, ''),
     const updatedAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '')
    
      await queryInterface.bulkInsert('Classes', [
        {
          name: '박수근 화백의 작품과 함께하는 덕수궁 나들이',
          price: 21900 ,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 1,
          regionId: '',
        },
        {
          name: '오일 파스텔 정규 클래스',
          price: 32000,
          type: '0',
          discount: 8,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 2,
          regionId: '',
        },
        {
          name: '보태니컬 아트 정규 클래스',
          price: 32000,
          type: '0',
          discount: 8,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 3,
          regionId: '',
        },
        {
          name: '소묘 클래스',
          price: 28800,
          type: '0',
          discount: 15,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 4,
          regionId: '',
        },
        {
          name: '마카로 그린 여행 스케치 달력 만들기',
          price: 23000,
          type: '0',
          discount: 11,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 5,
          regionId: '',
        },
        // 공예
        {
          name: '홈가드닝 클래스',
          price: 29000,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 6,
          regionId: '',
        },
        {
          name: '한지 공예 클래스',
          price: 22900,
          type: '0',
          discount: 11,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 6,
          regionId: '',
        },
        {
          name: '라탄으로 손가방 만들기',
          price: 24000,
          type: 0,
          discount: 20,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 7,
          regionId: '',
        },
        // 커리어
        {
          name: '예술 치유 클래스 - 수고했어, 나의 인생',
          price: 33900,
          type: 0,
          discount: 5,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 2,
          regionId: '',
        },
        {
          name: '중년, 다시 비상을 꿈꾸다', // 50+
          price: 0, //무료
          type: '0',
          discount: 0,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 8,
          regionId: '',
        },
        {
          name: '중장년 창업을 위해 필요한 기초지식', // 50+
          price: 0, // 무료
          type: '0',
          discount: 0,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 8,
          regionId: '',
        },
        {
          name: '치매노인 돌봄을 위한 존업케어의 실천', // 50+
          price: 19800,
          type: '0',
          discount: 30,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 9,
          regionId: '',
        },
        {
          name: '유투브 구독자에서 크리에이터로 도전하기', // 50+
          price: 17900,
          type: '0',
          discount: 20,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 10,
          regionId: '',
        },
        {
          name: '개인 브랜딩을 위한 블로그 첫 단계 시작하기', // 50+
          price: 17900,
          type: '0',
          discount: 20,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 10,
          regionId: '',
        },
        {
          name: '취업을 위한 퍼스널 이미지스타일링', // 50+
          price: 21000,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 11,
          regionId: '',
        },
        {
          name: '핵심기능으로 시작하는 디지털 세상 입문', // 50+
          price: 9000,
          type: '0',
          discount: 15,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 12,
          regionId: '',
        },
        {
          name: '바리스타 라떼아트 과정', // 50+
          price: 23000,
          type: '0',
          discount: 8,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 13,
          regionId: '',
        },
        // 운동/건강
        {
          name: '활기찬 아침을 위한 아침 명상',
          price: 19800,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 14,
          regionId: '',
        },
        {
          name: '마음을 가볍게하는 요가 클래스',
          price: 19800,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 14,
          regionId: '',
        },
        // 음료, 요리
        {
          name: '발렌타인데이 특집 브라우니 만들기',
          price: 5000,
          type: '0',
          discount: '',
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 15,
          regionId: '',
        },
        {
          name: '몸 속의 독소를 제거해주는 건강쥬스 만들기',
          price: 23500,
          type: '0',
          discount: 5,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 14,
          regionId: '',
        },
        {
          name: '마법반찬 든든한 밥상',
          price: 15900,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 12,
          regionId: '',
        },
        {
          name: '집에서 간단히 홈베이킹',
          price: 18300,
          type: '0',
          discount: '12',
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 13,
          regionId: '',
        },
        // 음악
        {
          name: '금요일 마다 색소폰 배우기',
          price: 27000,
          type: '0',
          discount: '',
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 15,
          regionId: '',
        },
        {
          name: '벨칸토 성악교실',
          price: 19800,
          type: '0',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 16,
          regionId: '',
        },
        // 오프라인
        // 서울 1
        {
          name: '꽃청 소믈리에',
          price: 20000,
          type: '1',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 14,
          regionId: 1,
        },
        {
          name: '놀이돌봄 선생님 양성과정',
          price: 0,
          type: '1',
          discount: 0,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 16,
          regionId: 1,
        },
        {
          name: '관계를 잇는 질문 대화법',
          price: 0,
          type: '1',
          discount: 0,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 16,
          regionId: 1,
        },
        {
          name: '쉽고 재미있는 미술작품 보고 느끼기',
          price: 9000,
          type: '1',
          discount: 5,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 17,
          regionId: 1,
        },
        {
          name: '50+를 위한 생활형 재무설계',
          price: 27000,
          type: '1',
          discount: '',
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 18,
          regionId: 1,
        },
        // 경기 2
        {
          name: '몸과 마을을 바로 잡는 기체조',
          price: 5000,
          type: '1',
          discount: 5,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 19,
          regionId: 2,
        },
        {
          name: '바리스타 2급 자격증 과정',
          price: 15000,
          type: '1',
          discount: 30,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 13,
          regionId: 2,
        },
        {
          name: '줄리 하프 배우기',
          price: 26000,
          type: '1',
          discount: 20,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 16,
          regionId: 2,
        },
        {
          name: '쭈니네 가죽놀이',
          price: 23000,
          type: '1',
          discount: 15,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 3,
          regionId: 2,
        },
        // 인천 3
        {
          name: '실버 교구 놀이',
          price: 0,
          type: '1',
          discount: 0,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 4,
          regionId: 3,
        },
        {
          name: '뮤직 테라피-음악과 두뇌 트레이닝',
          price: 24900,
          type: '1',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 11,
          regionId: 3,
        },
        // 전라도 4
        {
          name: '재미있는 명리학 입문',
          price: 21000,
          type: '1',
          discount: 5,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 18,
          regionId: 4,
        },
        // 충청도 5
        {
          name: '나만의 감성이 담긴 독창적인 사진 찍기',
          price: 16000,
          type: '1',
          discount: 20,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 12,
          regionId: 5,
        },
        {
          name: '모던민화-꽃 중의 꽃, 모란을 그리다',
          price: 19800,
          type: '1',
          discount: 23,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 9,
          regionId: 5,
        },
        // 경상도 6
        {
          name: '홈 바리스타-집에서 커피 브루잉',
          price: 15000,
          type: '1',
          discount: 10,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 13,
          regionId: 6,
        },
        {
          name: '꼼지락 손뜨개',
          price: 28900,
          type: '1',
          discount: 12,
          img_url: '',
          cotents: '',
          createdAt,
          updatedAt,
          teacherId: 12,
          regionId: 6,
        }
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
