'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     */
     const updatedAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '')
     const createdAt = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '')

     await queryInterface.bulkInsert('Users', [
       {
        login_id: 'rladidgu3',
        password: '1234qwer!',
        nickname: 'didgus',
        name: '김양현', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/%EC%A6%9D%EB%AA%85%EC%82%AC%EC%A7%84.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'gus99',
        password: '1234qwer!',
        nickname: 'didgus',
        name: '숙명희', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/user2.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'loocia',
        password: '1234qwer!',
        nickname: 'dhewk',
        name: '한옥희', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/user3.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'hellya',
        password: '1234qwer!',
        nickname: 'hello123',
        name: '박광애', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/user4.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'aawma',
        password: '1234qwer!',
        nickname: 'dodka',
        name: '김남윤', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/user5.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'kjkj11',
        password: '1234qwer!',
        nickname: 'jjwong',
        name: '허지웅', 
        profile_url: 'https://senior-class.s3.ap-northeast-2.amazonaws.com/userProfile/user1.jpg',
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'yjji87',
        password: '1234qwer!',
        nickname: 'didgus12',
        name: '김동환', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'terra1',
        password: '1234qwer!',
        nickname: 'terra',
        name: '손건희', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'rjsgml8',
        password: '1234qwer!',
        nickname: 'wkwkdaus',
        name: '백승문', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'qortmd',
        password: '1234qwer!',
        nickname: 'ansans43',
        name: '안복자', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'qhrwk9870',
        password: '1234qwer!',
        nickname: 'qhrwk',
        name: '신영숙', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'dudtnr87',
        password: '1234qwer!',
        nickname: 'dudtnr2',
        name: '박길동', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'rlfehd12',
        password: '1234qwer!',
        nickname: 'rlfehddl',
        name: '박코딩', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'coding12',
        password: '1234qwer!',
        nickname: 'coding1',
        name: '안코딩', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'everyday12',
        password: '1234qwer!',
        nickname: 'everyday12',
        name: '안기준', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'strara1',
        password: '1234qwer!',
        nickname: 'strara1',
        name: '손말자', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'joy123',
        password: '1234qwer!',
        nickname: 'joy12',
        name: '이기쁨', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'happy67',
        password: '1234qwer!',
        nickname: 'happy67',
        name: '이순신', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'tnssud23',
        password: '1234qwer!',
        nickname: 'tnssus21',
        name: '김옥희', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
       {
        login_id: 'dhrgml87',
        password: '1234qwer!',
        nickname: 'dhrgml87',
        name: '구필모', 
        profile_url: null,
        is_teacher: false,
        createdAt,
        updatedAt,
       },
     ], {});
  },

  down: async (queryInterface, Sequelize) => {
     await queryInterface.bulkDelete('Users', null, {});
  }
};
